#version: '3.8'
version: '3.7'
volumes:
  mysql-db:
    driver: local
services:
  db:
    build: ./mysql
    image: demo-db:0.0.1
    restart: always
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ../log/mysql:/var/log/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: demo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
  app:
    build: ./java
    image: demo-app:0.0.1
    volumes:
      - ../:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ./gradlew clean bootRun